server:
  port: ${SERVER_PORT}
spring:
  application:
    name: task02
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
springdoc:
  api-docs:
    path: /doc-api
  swagger-ui:
    path: /swagger.html
