apiVersion: v1
kind: Secret
metadata:
  name: task02-secret
type: Opaque
data:
  POSTGRES_URL: {{ .Values.secret.db.url | b64enc | quote }}
  POSTGRES_PORT: {{ .Values.postgresql.service.port | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}