apiVersion: v1
kind: Service
metadata:
  name: task02-service
spec:
  selector:
    app: task02
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  type: {{ .Values.service.type }}